export const FORMULARIO_PROYECTO ='FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS ='OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO ='AGREGAR_PROYECTO';
export const MOSTRAR_ERROR= 'MOSTRAR_ERROR';
export const PROYECTO_ACTUAL ='PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
// Types para tareas

export const FORMULARIO_TAREA ='FORMULARIO_TAREA';
export const TAREAS_PROYECTO ='TAREAS_PROYECTO';
export const VALIDAR_TAREA= 'VALIDAR_TAREA';
export const AGREGAR_TAREA ='AGREGAR_TAREA';
export const TAREA_ACTUAL ='TAREA_ACTUAL';
export const ELIMINAR_TAREA= 'ELIMINAR_TAREA';
export const ESTADO_TAREA= 'ESTADO_TAREA';